---
version: 0.2

env:
  variables:
    AWS_DEFAULT_REGION: us-east-1
    ACCOUNTID: 065145552369

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $ACCOUNTID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com

  build:
    commands:
      - |
        if [ -d "events-api" ]; then
          echo "Building events-api"
          cd events-api
          IMAGE_REPO_NAME="api-1tevv"
          IMAGE_NAME="events-api"
          IMAGE_TAG="latest"
          docker build -t $IMAGE_REPO_NAME:$IMAGE_TAG .
          docker tag $IMAGE_REPO_NAME:$IMAGE_TAG $ACCOUNTID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:$IMAGE_NAME:$IMAGE_TAG
          docker push $ACCOUNTID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:$IMAGE_NAME:$IMAGE_TAG
        fi
      - |
        if [ -d "events-website" ]; then
          echo "Building events-website"
          cd events-website
          IMAGE_REPO_NAME="web-1tevv"
          IMAGE_NAME="events-web"
          IMAGE_TAG="latest"
          docker build -t $IMAGE_REPO_NAME:$IMAGE_TAG .
          docker tag $IMAGE_REPO_NAME:$IMAGE_TAG $ACCOUNTID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:$IMAGE_NAME:$IMAGE_TAG
          docker push $ACCOUNTID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:$IMAGE_NAME:$IMAGE_TAG
        fi

artifacts:
  files: []  