---
version: 0.2

version: 0.2

env:
  variables:
    AWS_DEFAULT_REGION: us-east-1
    ACCOUNTID: 065145552369

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $ACCOUNTID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com

  build:
    commands:
      - |
        case "$(basename $(pwd))" in
          "events-api")
            IMAGE_REPO_NAME="api-1tevv"
            ;;
          "events-website")
            IMAGE_REPO_NAME="web-1tevv"
            ;;
          *)
            echo "Unknown directory: $(basename $(pwd))"
            exit 1
            ;;
        esac
        IMAGE_TAG="latest"
        docker build -t $IMAGE_REPO_NAME .
        docker tag $IMAGE_REPO_NAME $ACCOUNTID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:$IMAGE_TAG
        docker push $ACCOUNTID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:$IMAGE_TAG

artifacts:
  files: [] 