---
version: 0.2

env:
  variables:
    AWS_DEFAULT_REGION: us-east-1
    ACCOUNTID: 065145552369
    IMAGE_REPO_NAME_WEB: web-1tevv
    SRC_WEB_FOLDER: events-website
    IMAGE_TAG: latest

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $ACCOUNTID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com

  build:
    commands:
      - |
        echo "Following below logic"
        if [ "$(basename $(pwd))" = "events-api" ]; then
        docker build -t $IMAGE_REPO_NAME_WEB .
        docker tag $IMAGE_REPO_NAME_WEB $ACCOUNTID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME_WEB:$IMAGE_TAG
        docker push $ACCOUNTID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME_WEB:$IMAGE_TAG
        else
        exit 1
        fi
        

artifacts:
  files: []