apiVersion: v1
kind: Service
metadata:
 labels:
   app: events-web-svc-bg
 name: events-web-svc-bg
spec:
 ports:
 - port: 80
   protocol: TCP
   targetPort: 8080
 selector:
   app: events-web-green #select blue or green
   ver: latest #select blue or green
 type: LoadBalancer
