apiVersion: apps/v1
kind: Deployment
metadata:
 labels:
   app: events-web
 name: events-web
spec:
 replicas: 4
 selector:
   matchLabels:
     app: events-web
 template:
   metadata:
     labels:
       app: events-web
   spec:
     containers:
     - image: 065145552369.dkr.ecr.us-east-1.amazonaws.com/events-website:2.0
       name: events-web
       ports:
       - containerPort: 8080
       env:
       - name: SERVER
         value: "http://events-api-svc:8082"
